trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: APIContractSecurityAudit@5
  inputs:
    platformServiceConnection: 'Demolabs'
    jsonReport: 'audit-action-report-$(Build.BuildId).json'
    sarifReport: 'audit-action-report-$(Build.BuildId).sarif'