name: '42c-bank'
services:

  database:
    # image: anthony42crunch/test42c:database
    build: ../app/seed-database
    container_name: mongo-db
    ports:
      - '27017:27017'
    restart: always
    command: mongod --quiet

  apiserver:
     # image: anthony42crunch/test42c
      build: ../app
      container_name: 42c-bank-api
      ports:
        - '3000:3000'
        - '443:443'
      depends_on:
        - database
      restart: always
      command: nodemon start